keys:
  # users
  - &husjon 4e7cfbe78c8f9c9d88d7599711fc4fb86e2f5279

  # hosts
  - &laptop 09bb80a35e897ec80bfe69fb18b99f71085358c0
  - &workstation b5e61a57a8efa6d02c545ea2ea40c867e87cd548

creation_rules:
  - path_regex: ^hosts/workstation/secrets.yaml$
    key_groups:
    - pgp:
      - *husjon
      - *workstation
  - path_regex: ^hosts/laptop/secrets.yaml$
    key_groups:
    - pgp:
      - *husjon
      - *laptop

  - path_regex: secrets\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *husjon
