keys:
  - &husjon_workstation b9159d884cf5058c6f88135ba04ddc0c7c45a0b5
  - &husjon_laptop a7700437742764815153cf00335fb76fbd3b5726

  - &server_workstation b5e61a57a8efa6d02c545ea2ea40c867e87cd548
  - &server_laptop 09bb80a35e897ec80bfe69fb18b99f71085358c0

creation_rules:
  - path_regex: secrets\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *husjon_workstation
      - *husjon_laptop
      - *server_workstation
      - *server_laptop
