keys:
  # users
  - &husjon 4e7cfbe78c8f9c9d88d7599711fc4fb86e2f5279
  - &husjon-work 1e115c8a3fcab6570801144406cdac82d9069c3a

  # hosts
  - &cache 3f04a2e00f3ee8745c73c3a061581b101cfd02c7
  - &laptop ca1a84cac46ce7df44aceb2c6a5c1193c6cfd149
  - &workstation b5e61a57a8efa6d02c545ea2ea40c867e87cd548
  - &laptop-sb a1e828ae5443623f3119fc6f9d66d90b95cfdc6c
  - &workstation-sb ede92810862c3271fe57418fe874b4f2de372305

creation_rules:
  - path_regex: ^configuration/secrets/laptop.sops.yaml$
    key_groups:
    - pgp:
      - *husjon
      - *laptop
  - path_regex: ^configuration/secrets/workstation.sops.yaml$
    key_groups:
    - pgp:
      - *husjon
      - *workstation
  - path_regex: ^configuration/secrets/laptop-sb.sops.yaml$
    key_groups:
    - pgp:
      - *husjon
      - *husjon-work
      - *laptop-sb
  - path_regex: ^configuration/secrets/workstation-sb.sops.yaml$
    key_groups:
    - pgp:
      - *husjon
      - *husjon-work
      - *workstation-sb

  - path_regex: ^hosts/servers/cache.husjon.xyz/secrets.yaml$
    key_groups:
    - pgp:
      - *husjon
      - *cache

  - path_regex: secrets\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *husjon
