# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-9fdb09c9-6cbc-4434-9205-794ec12ddc37";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-9fdb09c9-6cbc-4434-9205-794ec12ddc37".device = "/dev/disk/by-uuid/9fdb09c9-6cbc-4434-9205-794ec12ddc37"; # root
  boot.initrd.luks.devices."luks-539c7144-b3ba-4a3d-ac48-a486d27dd8e8".device = "/dev/disk/by-uuid/539c7144-b3ba-4a3d-ac48-a486d27dd8e8"; # swap

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/ADF8-E324";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ { device = "/dev/mapper/luks-539c7144-b3ba-4a3d-ac48-a486d27dd8e8"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u1u2u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
