# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-9fdb09c9-6cbc-4434-9205-794ec12ddc37";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-9fdb09c9-6cbc-4434-9205-794ec12ddc37".device =
    "/dev/disk/by-uuid/9fdb09c9-6cbc-4434-9205-794ec12ddc37";
  boot.initrd.luks.devices."luks-539c7144-b3ba-4a3d-ac48-a486d27dd8e8".device =
    "/dev/disk/by-uuid/539c7144-b3ba-4a3d-ac48-a486d27dd8e8";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/ADF8-E324";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ { device = "/dev/mapper/luks-539c7144-b3ba-4a3d-ac48-a486d27dd8e8"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
