# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/21a95182-2897-4b0a-8984-6188490685bd";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-782ca1d2-3479-4036-8481-31461ccc158f".device = "/dev/disk/by-uuid/782ca1d2-3479-4036-8481-31461ccc158f"; # root
  boot.initrd.luks.devices."luks-f007be40-f448-4e3c-abd9-53ca15d3f895".device = "/dev/disk/by-uuid/f007be40-f448-4e3c-abd9-53ca15d3f895"; # swap

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2F0A-EA0E";
    fsType = "vfat";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/1c221f46-59d3-4eb1-813f-dbe7f53b6f05"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u1u2u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
