# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b0066456-c9c3-49ec-84bd-20841296d4bf";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-a0c6af8e-bb70-4d8e-a51f-823102aa7eaa".device = "/dev/disk/by-uuid/a0c6af8e-bb70-4d8e-a51f-823102aa7eaa"; # root
  boot.initrd.luks.devices."luks-8f3147b4-85ae-4b2c-879a-6777927cf621".device = "/dev/disk/by-uuid/8f3147b4-85ae-4b2c-879a-6777927cf621"; # swap

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2BCB-7304";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/2d785b14-39ea-4048-9a0e-e2cecffb92c5"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
